[[project]]
name = "blackjade"
desc = "P2P (peer-to-peer) Blockchain implemented in Fullstack MERN (MongoDB, Express.js, React.js, Node.js)"
tags = ["blockchain", "blackjade", "mern"]
links = [
    {name = "github", url = "https://github.com/tatumroaquin/blackjade"},
]

[[project]]
name = "VWA-SSJI"
desc = "VWA (Vulnerable Web App), SSJI (Server-side JavaScript Injection), a PoC (proof of concept) application. I used to demonstrate code injection vulnerabilities"
tags = ["vwa", "vulnerable-web-app", "ssji"]
links = [
    {name = "github", url = "https://github.com/tatumroaquin/vwa-ssji"},
]

[[project]]
name = "#!/blog/tatum"
desc = "PoC (proof of concept) markdown blogging platform made in from the ground-up in the MERN (MongoDB, Express.js, React.js, Node.js) stack. Complete JWT (JSON Web Tokens) authentication system and email verification using AWS SES."
tags = ["blog", "markdown", "mern"]
links = [
    {name = "github", url = "https://github.com/tatumroaquin/mern-blog"},
]

[[project]]
name = "Sighfer"
desc = "A simple web app containing implementations of common encryption cipher algorithms. Vigenere, Atbash, ROT13, Polybius Square, Autokey, Caesar, Base64, Base32, etc..."
tags = ["cipher", "encryption"]
links = [
    {name = "github", url = "https://github.com/tatumroaquin/sighfer"},
    {name = "demo", url = "https://sighfer.vercel.app"},
]
